### ISSUE TITLE
More than 30 vulnerabilities found on "npm i" most of the packages are not supported please help bro 

### ISSUE THREAD

**Issue by satyammayy** [phaticusthiccy/WhatsAsenaDuplicated#107]
Please help

I am trying to deploy locally Can't pay heroku bills

i am using kali linux 

by the way i use parrot os too i use both

**Comment by phaticusthiccy** [comment]
### Hi @satyammayy 

##

I've stopped local installation for a while. Please, wait patiently during this time.

**Comment by satyammayy** [comment]
okhay

**Comment by satyammayy** [comment]
Bro But I really love that bot lol

**Comment by phaticusthiccy** [comment]
> Bro But I really love that bot lol

Thank for using WhatsAsena 💌

**Comment by kaweeshachamodq** [comment]
Fun
