### ISSUE TITLE
BRO PLEASE HELP my node version is 16   npm is also latest

### ISSUE THREAD

**Issue by satyammayy** [phaticusthiccy/WhatsAsenaDuplicated#108]
![Screenshot 2021-06-19 07:42:38](https://user-images.githubusercontent.com/84136113/122628155-25c04800-d0d2-11eb-9188-e8522d11dfb1.png)

**Comment by phaticusthiccy** [comment]
### Hi @satyammayy 

Currently I only see npm vulnerabilities.
You must explain your issues much better.

Here is the some fixing audit solution:
1) Using `npm audit fix --force`

> It would fix npm vulnerabilities.

2) Using `yarn install --no-audit`

> The yarn installation is faster than alternative npm installion and much safer.

##

Also you can use heroku method for easy installion:

1) Scanning the QR Code with [this](https://repl.it/@phaticusthiccy/WhatsAsena-QR) replit.
2) Deploying to heroku with [this](https://heroku.com/deploy?template=https://github.com/phaticusthiccy/WhatsAsenaDuplicated) button.
3) Opening [dynos](t.me/herokudynoonscraper) and doing dynorestart.
4) WhatsAsena ready to use.

Need more information? Check our [wiki!](https://github.com/phaticusthiccy/WhatsAsenaDuplicated/wiki)

**Comment by satyammayy** [comment]
Thanks Sir I will look to it again thanks a lot
