### ISSUE TITLE
Local Installation Issue - Stucks on Loading X Language

### ISSUE THREAD

**Issue by satyammayy** [phaticusthiccy/WhatsAsenaDuplicated#113]
I did
yarn install 
node qr.js
and then 
node bot.js
i didn't make changes to config.js

**Comment by phaticusthiccy** [comment]
Hi @satyammayy 

Can you send whole error code? It must throw error if it fails. 
I don't noticed any issues with local installation.

**Comment by satyammayy** [comment]
![yade](https://user-images.githubusercontent.com/84136113/122854097-d62b8780-d330-11eb-80a6-d5f7842720d7.png)

**Comment by satyammayy** [comment]
Been on this page for 30 minutes

And i cannot run the whole module on replit too

**Comment by phaticusthiccy** [comment]
Hi @satyammayy 

##
I will ask two things from you.

1) **Can you send your config.env file?**
2) **Is your ethernet connection stabil?**

**Comment by satyammayy** [comment]
sure i will send you !   Yes my connection is stable

**Comment by satyammayy** [comment]
ASENA_SESSION="ASENA;;;eyJjbGllbnRJRCI6IktGTjZ1eC9laGthREpOMTNCUG9HUnc9PSIsInNlcnZlclRva2VuIjoiMUBTeFpVK1hCaERreEJzMWJSMm1oV3JiYktDbytaU1RFQzdhbTZWR3VYcllaRExiY2dXUlV1U2VlSE1BMi9kcmZQcERVM3VHRTFmRXBrMlE9PSIsImNsaWVudFRva2VuIjoiOC9nM2VsNU9DVTlQcFBYeWFjdVZFZUJOMmFVdTFYY3A3MllRWmNMczdxND0iLCJlbmNLZXkiOiJSbWY0VmY4VFBBRTRCMnc1ZFJUdnBNZHE3a2xYRysyMW9lcUtkc0Q5eEJBPSIsIm1hY0tleSI6ImtjcWJvcTFJRytUVDE1WjFQWmNybEExM0lxd1NBMjNpQ2ZwOW1HVGd5U1k9In0="

**Comment by satyammayy** [comment]
is this enough ?

**Comment by phaticusthiccy** [comment]
No, you must add all required environment in config.env
If you don't know what these are, you can check app.json
You have to see **required: true** vars.

Also u shouldn't share your ASENA_SESSION. It would be very dangerous.

**Comment by satyammayy** [comment]
ok Sir let me try that

**Comment by satyammayy** [comment]
![image](https://user-images.githubusercontent.com/84136113/122857878-dfb7ee00-d336-11eb-95a4-2f4c69cbd16d.png)

**Comment by satyammayy** [comment]
Still doesn't solve
please help

**Comment by satyammayy** [comment]
Anyone ? help !

**Comment by satyammayy** [comment]
it still don't work sirr PLEASE HELP ! @phaticusthiccy @yusufusta @MuhammedKpln

**Comment by phaticusthiccy** [comment]
Hi @satyammayy 

Sorry for late reply. Are you setted HEROKU=false in environment?

**Comment by Suryapardana** [comment]
How do I solve it, I'm also experiencing the same thing

**Comment by satyammayy** [comment]
it doesn't work help !

**Comment by phaticusthiccy** [comment]
> it doesn't work help !

https://github.com/phaticusthiccy/WhatsAsenaDuplicated/issues/113#issuecomment-869171656

**Comment by satyammayy** [comment]
iset the heroku =false
did not work
!

**Comment by phaticusthiccy** [comment]
> i set the heroku =false
> did not work
> !

Hi @satyammayy 

##

I will ask a few things from you.

1) First delete the directory.
2) Use git clone to create local fork .
3) Use npm install. If it won't work some npm packages, do this manually. Check package.json
4) Create an environment file including required configs. Check app.json
5) Send a screenshot inside your .env file. (Must be whole code)
6) Check your Heroku API key and app name.
7) [Open the dynos](t.me/herokudynoonscraper)
8) Check your ASENA_SESSİON and WhatsApp Web network.
9) Start the bot with node bot.js

##

It would be helpful.

**Comment by satyammayy** [comment]
i hae a previous version of WhatsAsena Duplicated It'os working let me use the old one thx !!

btw someone forked the old ersion i downloaded it from him!!!

**Comment by phaticusthiccy** [comment]
Hi @satyammayy 
##
Users cannot able to use old version of WhatsAsena. There is a rollback, but this things only available for who installed WhatsAsena on heroku. 
If you use fake versions of WhatsAsena, don't open issue here. Users may get confused.
I checked local installion. It's workins perfectly.

Now, ı tag this issue as stale. Conversation Locked.
