### ISSUE TITLE
".song" command not working

### ISSUE THREAD

**Issue by satyammayy** [phaticusthiccy/WhatsAsenaDuplicated#115]

**Comment by deereyeskart** [comment]
.song and .video  command not working.. Please solve this problem. .asena

**Comment by LuanRT** [comment]
This is a problem with the ytdl dependency, it can't download videos due to some changes on YouTube. You can either wait for it to be updated or try one of the temp fixes.

You can find more info and some workarounds here:
https://github.com/fent/node-ytdl-core/issues/939

**Comment by satyammayy** [comment]
npm i git://github.com/fent/node-ytdl-core.git#d1f535712410eebd79a7468abd07d94f8c4ebe5a

**Comment by phaticusthiccy** [comment]
Fixed!
