### ISSUE TITLE
NOT WORKINGGGGGGGG 

### ISSUE THREAD

**Issue by satyammayy** [phaticusthiccy/WhatsAsenaDuplicated#116]
root@ghost-Presario-CQ43-Notebook-PC:/home/ghost/try/WhatsAsenaDuplicated# node bot.js
You entered an invalid language. English language was chosen.
/home/ghost/try/WhatsAsenaDuplicated/node_modules/heroku-client/lib/request.js:255
    err = new Error(message)
          ^

Error: Expected response to be successful, got 404
    at Request.handleFailure (/home/ghost/try/WhatsAsenaDuplicated/node_modules/heroku-client/lib/request.js:255:11)
    at /home/ghost/try/WhatsAsenaDuplicated/node_modules/heroku-client/lib/request.js:148:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: 404,
  body: {
    id: 'not_found',
    message: 'The requested API endpoint was not found. Are you using the right HTTP verb (i.e. `GET` vs. `POST`), and did you specify your intended version with the `Accept` header?'
  }
}

**Comment by phaticusthiccy** [comment]
Duplicate #113
