### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by satyammayy** [phaticusthiccy/WhatsAsenaDuplicated#118]
root@ghost-Presario-CQ43-Notebook-PC:/home/ghost/pro/WhatsAsenaDuplicated# node bot.js
You entered an invalid language. English language was chosen.
/home/ghost/pro/WhatsAsenaDuplicated/node_modules/heroku-client/lib/request.js:255
    err = new Error(message)
          ^

Error: Expected response to be successful, got 404
    at Request.handleFailure (/home/ghost/pro/WhatsAsenaDuplicated/node_modules/heroku-client/lib/request.js:255:11)
    at /home/ghost/pro/WhatsAsenaDuplicated/node_modules/heroku-client/lib/request.js:148:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: 404,
  body: {
    id: 'not_found',
    message: 'The requested API endpoint was not found. Are you using the right HTTP verb (i.e. `GET` vs. `POST`), and did you specify your intended version with the `Accept` header?'
  }
}

**Comment by phaticusthiccy** [comment]
Please check #113 
Dont spam. If you continue this, ı will restric your issues.

**Comment by denomparkour** [comment]
Yes! Im getting this same issue in Heroku aswell as running locally. I found other issues but there is no proper answer. So commenting here. @phaticusthiccy.

**Comment by phaticusthiccy** [comment]
Reopened

**Comment by denomparkour** [comment]
> Hi @denomparkour
> 
> I added a .env example. Please check [it](https://github.com/phaticusthiccy/WhatsAsenaDuplicated/blob/master/example.env) and try again.

Hello @phaticusthiccy 
I don't think there is any issue in config.env. Because I renamed the example.env to config.env and then edited ASENA_SESSION.

And it's the same reason bot is not running on heroku too.

**Comment by phaticusthiccy** [comment]
Issue fixed. 
Have fun with WhatsAsena
