### ISSUE TITLE
Bot doesn't reply

### ISSUE THREAD

**Issue by Paresh-Maheshwari** [phaticusthiccy/WhatsAsenaDuplicated#12]
I an follow all steps. And make bot . after making bot i am send to command but bot is not reply to me

**Comment by phaticusthiccy** [comment]
> I an follow all steps. And make bot . after making bot i am send to command but bot is not reply to me
#
Please come [here](https://t.me/asenaremaster) and send me log. I have a few questions to ask first:

- 1) Where are you from?
- 2) What is the country code of the number you use?
- 3) Did you active dynos?
- 4) Did u check your dyno hours? 

For active dynos, Look at [this](https://t.me/herokudynoonscraper) link.

For check remaining dynos, Look at [this](https://devcenter.heroku.com/articles/free-dyno-hours) link.

**Comment by liodejulio** [comment]
Same with me, I did everything correctly couple times on 3 different devices, but  after the last step setting the heroku, the whatsapp web doesn't receive the update to start the bot.
Also I'm translating it to Portuguese Brazilian, but I couldn't test it yet :/

**Comment by phaticusthiccy** [comment]
> Same with me, I did everything correctly couple times on 3 different devices, but after the last step setting the heroku, the whatsapp web doesn't receive the update to start the bot.
> Also I'm translating it to Portuguese Brazilian, but I couldn't test it yet :/

Fixed Database Problem. Now you can easily setup WhatsAsena.
