### ISSUE TITLE
Unzip

### ISSUE THREAD

**Issue by sam-pandey** [phaticusthiccy/WhatsAsenaDuplicated#127]
Bro It's very necessary to have unzip plugin in WhatsAsena without any limit. I request about this feature/plugin telegram doesn't allow more than 2 GB of file

**Comment by phaticusthiccy** [comment]
Can You Explain It More? Like kinda usage, purpose of usage, what is needed for etc.

**Comment by sam-pandey** [comment]
> Can You Explain It More? Like kinda usage, purpose of usage, what is needed for etc.

hmm, Like telegram bots if i do /unzip link or by replying a file then it should send files to whatsapp Check @Catuserbot a telegram bot which has more features like g drive and mega too. That will be very helpful for all.

**Comment by phaticusthiccy** [comment]
WhatsApp dosent support sending folders. Even if I do that it will have to compress the file to send it. To explain briefly, WhatsApp framework baileys, supports such as these things: 
MessageType.text // MessageType.image // MessageType.document ... etc

We must use **MessageType.document** to send attached files. But this message type dosent support sending folders.

**Comment by citels-ops** [comment]
> WhatsApp dosent support sending folders. Even if I do that it will have to compress the file to send it. To explain briefly, WhatsApp framework baileys, supports such as these things:
> MessageType.text // MessageType.image // MessageType.document ... etc
> 
> We must use **MessageType.document** to send attached files. But this message type dosent support sending folders.

Ohh,is it possible to leech on whatsapp using r clone? 
It may be good

You should create an another repo just for plugins 
Then anyone can get access easily without checking gist .(suggestion)

**Comment by phaticusthiccy** [comment]
> > WhatsApp dosent support sending folders. Even if I do that it will have to compress the file to send it. To explain briefly, WhatsApp framework baileys, supports such as these things:
> > MessageType.text // MessageType.image // MessageType.document ... etc
> > We must use **MessageType.document** to send attached files. But this message type dosent support sending folders.
> 
> Ohh,is it possible to leech on whatsapp using r clone?
> It may be good
> 
> You should create an another repo just for plugins
> Then anyone can get access easily without checking gist .(suggestion)

Please, do not off topic conversation. You can create new issue. Templates are available.
