### ISSUE TITLE
BOT can't start  on whatsapp web after following the steps on the guide

### ISSUE THREAD

**Issue by liodejulio** [phaticusthiccy/WhatsAsenaDuplicated#13]
![Screenshot_20210204-121005_Brave](https://user-images.githubusercontent.com/77903525/106936770-96963300-66e2-11eb-9adb-16ff78fb542c.jpg)
 - ![Screenshot_20210204-121026_Brave](https://user-images.githubusercontent.com/77903525/106936791-9f870480-66e2-11eb-8784-699ae81efef6.jpg)
![Screenshot_20210204-121050_Brave](https://user-images.githubusercontent.com/77903525/106936810-a57ce580-66e2-11eb-837c-1c02d0f3ba9d.jpg)
![Screenshot_20210204-121127_Brave](https://user-images.githubusercontent.com/77903525/106936858-b4639800-66e2-11eb-972e-b6d75c3d95c9.jpg)
![Screenshot_20210204-121210_WhatsApp](https://user-images.githubusercontent.com/77903525/106936912-c34a4a80-66e2-11eb-87eb-29b11f316d09.jpg)

I followed the steps on guide on my PC, and 2 different Android devices, but can't my WhatsApp don't receive the last update after set up the heroku app, also I tried on whatsapp business, but I had the same problem.

**Comment by phaticusthiccy** [comment]
Firstly, this is not the log section. If u see the worker log please follow this steps:

1.  Hit the `More` button.
2. Tap the `Restart All Dynos`
3. Wait a couple
4. Type `.alive` any chat.

If still not working, follow these:

1.  Tap the `More` button.
2. Tap `View Log`
3. Tap `Save` Button
4. Send me log. 

• E-mail: birhic023@gmail.com
• Telegram: https://t.me/phaticusthiccy
• Support Group: https://t.me/asenaremaster

Aslo check this:

1. If your number doesn't start with +1, you must choose Europa when you deploying the bot.
2. If you using English language, please use LANGUAGE = en (lowercase character)
3. If you using SUDO mod, plase dont type “+” or u can change it to true. SUDO = true

If everything pass, check your String Session, HEROKU_APP_NAME and HEROKU_API_KEY

**Comment by liodejulio** [comment]
I'll redo all the steps carefully, if it doesn't work, I'll contact you by sending you the log.
I appreciate your help !

**Comment by phaticusthiccy** [comment]
Im waiting ur message :)

**Comment by phaticusthiccy** [comment]
> I'll redo all the steps carefully, if it doesn't work, I'll contact you by sending you the log.
> I appreciate your help !

Fixed Database Problem. Now you can easily setup WhatsAsena.
