### ISSUE TITLE
Thanks for 70.000 User - WhatsAsena 

### ISSUE THREAD

**Issue by phaticusthiccy** [phaticusthiccy/WhatsAsenaDuplicated#134]
## Hello Guys

I am so excited to write these sentences. WhatsAsena has more than **70.000** user. Yess, we reached it! I am so so so glad to see that 🥰

All the work and effort we have done so far was only for thanks. And that will never change. This adventure, which started about 7 months ago, continues today as the most used UserBot in the world. 

Special thanks to all users, developers, who tryna to help us. Also advertisers :)

##

## The Beginning of the Adventure 

I'm writing these words as  me, Thiccy. Previously I was just a developer on the AsenaDev team. The real thing I do is code artificial intelligence algorithms. The neural ai. After working with my team and its founder, [Yusuf](github.com/yusufusta), for a while. He said he was going to make a new UserBot and it would be the first in the world. This is how I met WhatsAsena. 
Now we are here, World First Userbot for WhatsApp - WhatsAsena

##

## Development - Users 

I've been helping develop this project since it started. Months ago we decided to stop development for various reasons. I talked to the founder [Yusuf](github.com/yusufusta) and said that I want to continue this project. I've been trying to develop by myself since the about 5 month ago. I would like to thank the people who helped me in this process. 
I tried to add many things that would be nice for users to the WhatsAsena. I always tried to do my best. There were those who wanted to steal, there were those who tried to deceive people by creating false reality. They need to learn that the summit is solitary and unique.

## Future of WhatsAsena and Continuing Projects

I will continue to improve the WhatsAsena as long as I live. I know you want new features, we have plenty of time, we have excitement. We need time for everything to work out, Patience is only for winners. 
As I said above, as long as I live, the WhatsAsena will not remain unowned. If I ever stop improving, make sure everything is as it should be. And my main job is to get back to AI development. 

## Final Words  
I would like to end this article with the following sentences.

Just follow your dreams. Don't steal, help. Do not belittle, be indulgent and the most important thing never give up. Just give it time. 
I love y'all so much ❤️ The target is 200 thousand user 😂
Have a nice day.

**Comment by shadokiller** [comment]
🔥

**Comment by s8nzephan** [comment]
Thank you for your work lub u ❣️

**Comment by mrsauravkr1** [comment]
Thank you so much man, for all your hard work.Also you're working on Instagram bot, I'm so excited to try that too.❤️

**Comment by fasilvkn** [comment]
💕♥️

**Comment by kartikey15** [comment]
Glad to be one of the proud users! 💯❤️🔥

**Comment by Arjun1234arjun** [comment]
- [x] Nic bot❤❤❤❤

**Comment by Dularazero** [comment]
💖🔥

**Comment by phaticusthiccy** [comment]
> 🔥

💯

**Comment by phaticusthiccy** [comment]
> Thank you for your work lub u ❣️

Not at all :) ❤️

**Comment by phaticusthiccy** [comment]
> Thank you so much man, for all your hard work.Also you're working on Instagram bot, I'm so excited to try that too.❤️

❤️ Snippet 😂

**Comment by Surya2546** [comment]
Congratulations 😃😃🤩🤩 bring more amazing plugins😇

**Comment by jacktheboss220** [comment]
🎉🥳🔥🔥🔥

**Comment by ritz0007** [comment]
Thank you so much AsenaDev and team, you guys are just amazing. Just coz of y'all efforts we get an opportunity to get interact with this beauty of technology. 

You're amazing, keep growing LOVE your work❤

**Comment by phaticusthiccy** [comment]
> Thank you so much AsenaDev and team, you guys are just amazing. Just coz of y'all efforts we get an opportunity to get interact with this beauty of technology.
> 
> You're amazing, keep growing LOVE your work❤

Thank you so much 💗

**Comment by JERIN-SER** [comment]
Malayalees indo😎⚡

**Comment by RHYTHMHACKER** [comment]
There is A Problem in Downloading Video using .video command from YouTube since short videos use different type of share link and it's Slow In Downloading But you WhatsApp Bot is Amazing 🤩💕 Just Adda A Feature To customized Audio Bgms💘

**Comment by Farhan-Malik** [comment]
Congrats....❤️❤️

**Comment by TOXIC-DEVIL** [comment]
> ## Hello Guys
> I am so excited to write these sentences. WhatsAsena has more than **70.000** user. Yess, we reached it! I am so so so glad to see that 🥰
> 
> All the work and effort we have done so far was only for thanks. And that will never change. This adventure, which started about 7 months ago, continues today as the most used UserBot in the world.
> 
> Special thanks to all users, developers, who tryna to help us. Also advertisers :)
> 
> ## The Beginning of the Adventure
> I'm writing these words as me, Thiccy. Previously I was just a developer on the AsenaDev team. The real thing I do is code artificial intelligence algorithms. The neural ai. After working with my team and its founder, [Yusuf](github.com/yusufusta), for a while. He said he was going to make a new UserBot and it would be the first in the world. This is how I met WhatsAsena.
> Now we are here, World First Userbot for WhatsApp - WhatsAsena
> 
> ## Development - Users
> I've been helping develop this project since it started. Months ago we decided to stop development for various reasons. I talked to the founder [Yusuf](github.com/yusufusta) and said that I want to continue this project. I've been trying to develop by myself since the about 5 month ago. I would like to thank the people who helped me in this process.
> I tried to add many things that would be nice for users to the WhatsAsena. I always tried to do my best. There were those who wanted to steal, there were those who tried to deceive people by creating false reality. They need to learn that the summit is solitary and unique.
> 
> ## Future of WhatsAsena and Continuing Projects
> I will continue to improve the WhatsAsena as long as I live. I know you want new features, we have plenty of time, we have excitement. We need time for everything to work out, Patience is only for winners.
> As I said above, as long as I live, the WhatsAsena will not remain unowned. If I ever stop improving, make sure everything is as it should be. And my main job is to get back to AI development.
> 
> ## Final Words
> I would like to end this article with the following sentences.
> 
> Just follow your dreams. Don't steal, help. Do not belittle, be indulgent and the most important thing never give up. Just give it time.
> I love y'all so much ❤️ The target is 200 thousand user 😂
> Have a nice day.

Congratulation 💕

**Comment by Nandhuser** [comment]
😊

**Comment by saneej** [comment]
> Malayalees indo😎⚡

Illathirikkuo

**Comment by saneej** [comment]
[Congratulations 🍺🏆](http://instagram.com/saneejified) […….](http://instagram.com/saneejified)

**Comment by abdurehmanoff** [comment]
🥳🔥🔥🔥

**Comment by ak-kaddu** [comment]
@phaticusthiccy congratulations bro ❤️❤️
I hope you reach your next goal of 200k soon .
Keep developing stay healthy .
![FB_IMG_16265925064081643](https://user-images.githubusercontent.com/85445275/126074719-a559070f-f7c3-475d-913c-b7e5cbbb5e45.jpg)
A little security guard for you and your team
On behalf of every asena user

**Comment by Madmaddy7** [comment]
😍😍😍😍😍😍😍😍

**Comment by Madmaddy7** [comment]
L

**Comment by phaticusthiccy** [comment]
> @phaticusthiccy congratulations bro ❤️❤️
> I hope you reach your next goal of 200k soon .
> Keep developing stay healthy .
> ![FB_IMG_16265925064081643](https://user-images.githubusercontent.com/85445275/126074719-a559070f-f7c3-475d-913c-b7e5cbbb5e45.jpg)
> A little security guard for you and your team
> On behalf of every asena user

Kitty kitty 🐈
Thank you so much 💞

**Comment by phaticusthiccy** [comment]
Guuuys, there has been a really rapid development. 4000 new users have started using [WhatsAsena](https://github.com/phaticusthiccy/WhatsAsena) since I posted this announcement. I can't believe it, ı think ı fell in love with this situation 😆
Also ı must say, after this moment, we are in the JavaScript Global Trend List. I am very very veeery happy 😁. 

Lemme say, the target is 200K!? 🙄 Yo it's toooo nominal value 🤭
Have a nice day, Hope to meet you guys when we reached the goal. ❤️

**Comment by Nikhil-Jr** [comment]
Hi

**Comment by deep0708** [comment]
Hi, congratulations on reaching 70K users landmark, this is just the beginning. I have a little query although i know this is not the proper place or time to ask such a thing but I can't help but wonder why some commands which should be accessed by public atleast the admins of the group can't use them. For example : adding filter or note. It can only be done the user who has the bot merged to his mobile number. Also the add command doesn't work. It doesn't add anyone. I followed proper syntax. Please take a look at this if you have some time. Thanks and again congratulations. Cheers.

**Comment by Abusire** [comment]
> Malayalees indo😎⚡

Und aliyaa

**Comment by phaticusthiccy** [comment]
> Malayalees indo😎⚡

WhatsAsena has 75.000 user with more than 40 countries. Turkey, Germany, Sri Lanka, Indian, Russia .. 
Believe that there are not many users in your country. About %9 Users use Heroku to deploy WhatsAsena. %91 users use WhatsAsena on their local servers or vds, vps etc.
Let's not personalize it :)
Have a nice day 😊

**Comment by phaticusthiccy** [comment]
> Hi, congratulations on reaching 70K users landmark, this is just the beginning. I have a little query although i know this is not the proper place or time to ask such a thing but I can't help but wonder why some commands which should be accessed by public atleast the admins of the group can't use them. For example : adding filter or note. It can only be done the user who has the bot merged to his mobile number. Also the add command doesn't work. It doesn't add anyone. I followed proper syntax. Please take a look at this if you have some time. Thanks and again congratulations. Cheers.

Thanks for precious comment 💖
You can open an issue for these bugs :) 
See ya 💌

**Comment by Mikhaiel** [comment]
Love from Kerala 🤸 ♥️ ♥️ ♥️

**Comment by phaticusthiccy** [comment]
Closed! 
Love Y'all 💕

Don't be upset. We will meet again. Goal 200.000 User 😉

**Comment by Amaluamal** [comment]
Poli thanne
Machaane
