### ISSUE TITLE
A simple suggestion

### ISSUE THREAD

**Issue by albiahbi** [phaticusthiccy/WhatsAsenaDuplicated#147]
Can you guys add a feature to make api calls..?

I'm not a programmer** Though I just wonder, if you guys can somehow connect Whatsasena with dialogflow...? You may already know how useful it can be to fully automate tasks as well as it can be a good personal assistant like "JARVIS" Just some thoughts... I'm learning things, and I'm trying to do the same... Somehow connect these two together... If I succeed I'll surely let you know... Meanwhile a good programmer like you don't have to struggle like I'm doing to achieve this... You could just code few lines and viola... 

Hope you consider my suggestion... Ba-bye...

**Comment by phaticusthiccy** [comment]
Hi @albiahbi 

##

Thank for this suggestion. Maybe you know, WhatsAsena has **Eva** Neural Machine Learning AI.
You can call her start message via **Eva**
To tell the truth, ı don't know anything about Jarvis AI. 

You wrote things about Google Dialogflow.
It has CX and ES agents to call as an API. Both agents are the paid. Only ES agent has free trail. 

![IMG_20210725_144607](https://user-images.githubusercontent.com/74794033/126897871-f289cb80-68e8-45bc-ad52-5629784d88b7.jpg)


![IMG_20210725_144624](https://user-images.githubusercontent.com/74794033/126897875-d01f07eb-8d5e-4f96-bdfd-bb0c44c0c6e0.jpg)


![IMG_20210725_144639](https://user-images.githubusercontent.com/74794033/126897880-b0d63a9c-74b1-4144-b9e3-f4ff22507fe3.jpg)


##

If it is possible to add Dialogflow to WhatsAsena, ıt can only be a Chatbot. WhatsAsena has no access to any device. Eva or me or someone else.. We can't access user's device.
Eva is already powerful conversational AI. ( Actually Eva is my personal assistant like siri, ı cloned %5 data to make ai chatbot ) 
Also may u know it. Google Cloud APIs are not free. 

![IMG_20210725_145447](https://user-images.githubusercontent.com/74794033/126898056-ca62c4d0-5690-4484-ba34-e48b6830fbff.jpg)

This value is the required for the servers to run. It can't get any cheaper than this value. Who wanna to pay this for only chatbot. We have **Eva** Already. 

I hope you don't misunderstand what I'm saying. 
Have a nice day, love yaa 💕

**Comment by albiahbi** [comment]
@phaticusthiccy I really appreciate your time for giving me such useful information... Thank you...

**Comment by phaticusthiccy** [comment]
Your Welcome ☺️
