### ISSUE TITLE
by typing help it starts spamming it

### ISSUE THREAD

**Issue by Froz3enBOY** [phaticusthiccy/WhatsAsenaDuplicated#154]
**Describe the bug**
whenever i write .help it starts spamming all the msgs without any stop , no commands work after that

##

**Expected behavior**

##

**Screenshots**

##

**Users, please complete the following actions.**
- WhatApp Package Name
- WhatsAsena Version
- Work Type (Private || Public)

##

**Additional context**
![Screenshot_2021-08-01-11-13-46-795_com whatsapp w4b](https://user-images.githubusercontent.com/87743419/127760583-5d599a65-6429-4da1-92c1-97bdf17b9540.jpg)
![Screenshot_2021-08-01-11-13-44-637_com whatsapp w4b](https://user-images.githubusercontent.com/87743419/127760585-ce1fd146-1f12-4c70-a465-99400d1fdd4e.jpg)

**Comment by phaticusthiccy** [comment]
Hi @Froz3enBOY 

##

I have some questions. 

- Firstly, does this error appear when you use only this command? Do other commands have this problem?
- What is the worktype of bot? You described "Public or Private" but it must be one. Use `.getvar WORK_TYPE` to see bot's worktype.

**Comment by Froz3enBOY** [comment]
> Hi @Froz3enBOY
> 
> I have some questions.
> 
> * Firstly, does this error appear when you use only this command? Do other commands have this problem?
> * What is the worktype of bot? You described "Public or Private" but it must be one. Use `.getvar WORK_TYPE` to see bot's worktype.

only happening in help command others working well 
bot worl type is public

**Comment by Froz3enBOY** [comment]
hey solve this 😭

**Comment by phaticusthiccy** [comment]
Hi @Froz3enBOY 

##

Here is the some solutions for this issue:

- [Restarting Dynos](https://t.me/AsenaSupport/1434161)
- Checking Ping by Typing **.ping** ( It Wouldn't be higher than 450-500)
- Using SIGTERM Reset by Typing **.restart**

##

Also **.help** command is not effective. I must improve it. So u don't need to use it :)

**Comment by citels-ops** [comment]
> Hi @Froz3enBOY
> 
> Here is the some solutions for this issue:
> 
>     * [Restarting Dynos](https://t.me/AsenaSupport/1434161)
> 
>     * Checking Ping by Typing **.ping** ( It Wouldn't be higher than 450-500)
> 
>     * Using SIGTERM Reset by Typing **.restart**
> 
> 
> Also **.help** command is not effective. I must improve it. So u don't need to use it :)

perhaps he is not using Official One, Maybe he has changed code spam to help,from where he has deployed
