### ISSUE TITLE
Let's Talk About Cyber Attack Protection System 🛡️

### ISSUE THREAD

**Issue by phaticusthiccy** [phaticusthiccy/WhatsAsenaDuplicated#169]
# Hi Guys 👋🏻 

Our topic today is the cyber attack protection system that many people are curious about. I received a lot of review requests for this topic, let's start.

##

## What does Cyber ​​Attack Protection System Mean? 💬

The purpose of this tool is to protect your device from all possible attacks via WhatApp or WhatApp Web servers. 
Cyber attack, possible memory leaks, bypass, bruteforce etc.

## So How Does This Tool Work? 🛠️

I'll tell you how this works in step by step.
- Firstly, data is retrieved from Dockerhub. 
- Several intermediate codes are run after data is received.
- At this time, the compatibility of the original repository in docker with the data transferred repository is checked.

**If the data is not compatible after this stage, the linked situation will occur.** (`Fake Bots? Do they have this feature? 🚫` Check This Title)

- A cyber-attack protection system is prepared, which will be activated every second when pairing is achieved.
- If all transactions are Ok, It will be active after WhatsAsena starts.

## How It Protects? ⚠️

This tool can detect even the smallest attacks as it works every second. When WhatsApp or user's phone receive an attack, it immediately follows these steps:

- Closing all possible ports.
- Stops all streaming lines.
- Bot makes itself inactive.
- All traffic is re-encrypted.
- By this time the attacker has already been sent out of connection.
- Reconnects to WhatsApp
- An immaculate environment is re-established.

## Fake Bots? Do they have this feature? 🚫
No, all fake bots using our docker. This feature only for original WhatsAsena. So what can we talk about fake bots? Let's explain.

- If the repository does not match, all ports are opened first.
- Then the necessary actions that protect the bot and the device are bypassed.
- Users are extremely endangered as there is no longer any  protecting the bot and the user.

Many users came with this complaint, it's not our responsibility. Fake bots are very dangerous for users in terms of security. 

## Does This System Protect My Phone 24/7? ⌛
Yes or no, There is no complete answer to this question. For now.. 
WhatApp web needs constant internet connection to work so try to keep the bot active 24/7. With the new WhatsApp updates, WhatsApp Web will be able to work without internet.
##

If you have any questions or any questions you want to ask, I waiting for your comments. 

Have a nice day. 
Love y'all 💕

**Comment by Sb-4Ma6DE5H** [comment]
hai ninte bot kollam ninte number onn tharoo owner number

**Comment by Sb-4Ma6DE5H** [comment]
hai ninte bot kollam ninte number onn tharoo owner number

**Comment by Salman10salu** [comment]
Issue vann
