### ISSUE TITLE
GanStyle AI

### ISSUE THREAD

**Issue by happuji** [phaticusthiccy/WhatsAsenaDuplicated#17]
What is gan style

**Comment by phaticusthiccy** [comment]
### Hi @happuji 😊

##

> GanStyle AI
*The purpose of this artificial intelligence is to combine two photos with neural networks. You will see* `GAN_IMAGE` *section on the* **Config Vars**. *You can change it whatever you want. But one thing ı need to say, Image link must have the format name at the end.*
**Example:** 
```js
"https://domain.jpg"
"https://domain.png"
...
```
##

##### Usage 

*You can use this plugin with type* `.ganstyle`
**Here are some examples for you:**

![IMG_20210209_023305](https://user-images.githubusercontent.com/74794033/107294968-7e763900-6a7f-11eb-8bd7-d61d836a93c5.jpg)

![IMG_20210209_023501](https://user-images.githubusercontent.com/74794033/107294994-8afa9180-6a7f-11eb-92a4-d2598c652fa6.jpg)

![SAVE_20210209_023627](https://user-images.githubusercontent.com/74794033/107295042-a2397f00-6a7f-11eb-8363-840306106c92.jpg)

##

**Comment by happuji** [comment]
You are the best for us 
Lots of love for u

**Comment by phaticusthiccy** [comment]
**Thanks for Using WhatsAsena :)**
*Also you can change whatever you want GAN_IMAGE in Config Vars.*

Have a nice day.

**Comment by happuji** [comment]
Yes ok but I check update  and it shows thre is some thing likt theme update jinkled like I don't remember it properly coz I updated it already but nothing changes tell me the truth..

**Comment by phaticusthiccy** [comment]
> Yes ok but I check update and it shows thre is some thing likt theme update jinkled like I don't remember it properly coz I updated it already but nothing changes tell me the truth..

#### Hi @happuji 

**WhatsAsena Duplicated keeps getting updates by me.**
*Let me explain to you about the updates:*

> UPDATE ICONS

```js
"There are several emoji next to the update message. Let me explain them"

'🥳 Emoji'
// This means there is a new plugin.

'🛠️ Emoji'
// This means needs something fixed or something under maintenance.

'📢 Emoji'
// This means a new version has arrived.

'⚠️ Emoji'
// This means something is don't work anymore. 
// Except when you type in .asena command.

// If there is any emojis, you can let go
```

*In this update I just changed the theme of the github.io page.*
*Have a nice day.*

**Comment by happuji** [comment]
Ok nice to tell me
