### ISSUE TITLE
Message no come

### ISSUE THREAD

**Issue by antriya** [phaticusthiccy/WhatsAsenaDuplicated#174]
**Describe the bug**

##

**Expected behavior**

##

**Screenshots**

##

**Users, please complete the following actions.**
- WhatApp Package Name
- WhatsAsena Version
- Work Type (Private || Public)

##

**Additional context**

**Comment by phaticusthiccy** [comment]
Please follow the desired answers. 
Fix it or open a new blank templated issue.
