### ISSUE TITLE
Other Admins cant use .ban and some of admin commands

### ISSUE THREAD

**Issue by Isath** [phaticusthiccy/WhatsAsenaDuplicated#175]
other admins cant use commands like .mute .spam .ban i need them to use those commands

**Comment by phaticusthiccy** [comment]
Hi @Isath 

##

The **public** mode doesn't support these features yet. I will add it soon as possible. 
Alternatively, you can use sudo to give permission. Please [check here.](https://github.com/phaticusthiccy/WhatsAsenaDuplicated/issues/16#issuecomment-774716316)

Have a nice day 👋🏻
