### ISSUE TITLE
only .help command is working

### ISSUE THREAD

**Issue by TOXIC-DEVIL** [phaticusthiccy/WhatsAsenaDuplicated#180]
### Discussed in https://github.com/phaticusthiccy/WhatsAsenaDuplicated/discussions/170

<div type='discussions-op-text'>

<sup>Originally posted by **Isath** August 11, 2021</sup>
![image_2021-08-11_131125](https://user-images.githubusercontent.com/44706480/128989596-167bc11e-c5c6-42c9-994d-540398486128.png)

only .help is working and when i gave any other command like.asena it gives this error </div>

I am also facing this issue @phaticusthiccy

**Comment by phaticusthiccy** [comment]
Hi @TOXIC-DEVIL 

Firstly, please check your WhatsAsena worktype. It must be **public** or **private**.
Secondly, WhatsAsena supports external additions. So, if you used unofficial plugins, this can cause error.
Thirdly and finally thing, please check your HANDLERS var.

**Comment by souravkl11** [comment]
@phaticusthiccy  My bot is still working when disappearing messages are turned on.

**Comment by TOXIC-DEVIL** [comment]
> Hi @TOXIC-DEVIL
> 
> Firstly, please check your WhatsAsena worktype. It must be **public** or **private**.
> Secondly, WhatsAsena supports external additions. So, if you used unofficial plugins, this can cause error.
> Thirdly and finally thing, please check your HANDLERS var.

Yes, my worktype is private & handler is ^[.] Then there is no other unofficial plugins! I have used this ropo, And i got this error!

**Comment by TOXIC-DEVIL** [comment]
> @phaticusthiccy My bot is still working when disappearing messages are turned on.

😨😨😨

**Comment by phaticusthiccy** [comment]
> @phaticusthiccy My bot is still working when disappearing messages are turned on.

Please don't be off-topic conversation. 
You can create a new discussion. [Click Here!](https://github.com/phaticusthiccy/WhatsAsenaDuplicated/discussions/new)

**Comment by phaticusthiccy** [comment]
> > Hi @TOXIC-DEVIL
> > Firstly, please check your WhatsAsena worktype. It must be **public** or **private**.
> > Secondly, WhatsAsena supports external additions. So, if you used unofficial plugins, this can cause error.
> > Thirdly and finally thing, please check your HANDLERS var.
> 
> Yes, my worktype is private & handler is ^[.] Then there is no other unofficial plugins! I have used this ropo, And i got this error! Also after turning on autobio i am facing!

Unfortunately, it is not possible to understand the error from the image you sent. Promise errors often occur due to a database. Database of DataTypes, Strings or any sequlize creations. 

Please check [these](https://t.me/asenaremaster/19107?single) steps. If the error still persists after this method, try reinstalling WhatsAsena. 
Once you've made the necessary edits, if it still doesn't work please reopen this issue.

**Comment by TOXIC-DEVIL** [comment]
> > > Hi @TOXIC-DEVIL
> > > Firstly, please check your WhatsAsena worktype. It must be **public** or **private**.
> > > Secondly, WhatsAsena supports external additions. So, if you used unofficial plugins, this can cause error.
> > > Thirdly and finally thing, please check your HANDLERS var.
> > 
> > 
> > Yes, my worktype is private & handler is ^[.] Then there is no other unofficial plugins! I have used this ropo, And i got this error! Also after turning on autobio i am facing!
> 
> Unfortunately, it is not possible to understand the error from the image you sent. Promise errors often occur due to a database. Database of DataTypes, Strings or any sequlize creations.
> 
> Please check [these](https://t.me/asenaremaster/19107?single) steps. If the error still persists after this method, try reinstalling WhatsAsena.
> Once you've made the necessary edits, if it still doesn't work please reopen this issue.

Ok
