### ISSUE TITLE
WhatsAsena Doesn't Work on Windows and Linux Devices

### ISSUE THREAD

**Issue by hellnodes** [phaticusthiccy/WhatsAsenaDuplicated#182]
`Linux:`
![image](https://user-images.githubusercontent.com/36241002/130589889-9a4d1850-a50c-4035-9ea8-c25279c1ee91.png)

`Windows:`
![image](https://user-images.githubusercontent.com/36241002/130589932-69264737-2af4-483c-b9fd-d4194b60a230.png)

`config.env:`
![image](https://user-images.githubusercontent.com/36241002/130590163-16fae4cb-2926-47d7-951a-0cdab5e58a0b.png)

`When Debug Mode Is Opened:`
![image](https://user-images.githubusercontent.com/36241002/130594798-c6b1e37a-29dc-4272-9696-27a6c3eb98b6.png)

**Comment by phaticusthiccy** [comment]
Hi @hellnodes 

Many changes have been made to WhatsAsena recently months. These innovations are used in systems that require more power, more storage and more connection speed. 

With Eva's neural artificial intelligence, this situation became even more necessary. The heroku servers. 

##

I see there are some config and dotenv issues. I aim to resolve this situation in the future. Until that day comes, please keep using heroku servers. It will be more convenient for you in every sense. 

##

I'll leave this topic untagged for now. I will stamp "fixed" in future updates.

**Comment by hellnodes** [comment]
my server is already fine, I just didn't want to use it because I can't perform instant transactions on heroku
looking forward to the next update.

**Comment by phaticusthiccy** [comment]
> my server is already fine, I just didn't want to use it because I can't perform instant transactions on heroku
> looking forward to the next update.

I understand your anxiety. The new update will come in a few days. It does not contain anything new about this problem that you and many others are experiencing. I'm trying to fix this problem and store the data in a healthy local area.

**Comment by hellnodes** [comment]
I reinstalled it on another server
and I edited the example.env you said as config.env
nothing has changed :/
![image](https://user-images.githubusercontent.com/36241002/131857823-1ce3b20e-72f1-41b3-a1ae-ceafacf9ded2.png)

**Comment by hellnodes** [comment]
I tried again after a long time and still the same :/
