### ISSUE TITLE
how to change few cmds names? pls help

### ISSUE THREAD

**Issue by jacktheboss220** [phaticusthiccy/WhatsAsenaDuplicated#185]
before 1.3.5 update i was able to makes few changes but it is not possible now.
pls help!!

**Comment by phaticusthiccy** [comment]
Hi @jacktheboss220 

WhatsAsena is completely open source project. But some reason we must restraint some changes. Many fake bots available. 
These fake bots are of great importance for the safety of users. None of them have an active cyber attack protection system. This means a huge security breach for those who use these fake bots.
If you want to contribute WhatsAsena, please open a pull request. Also you can check our contribution rules in Readme.

Have a nice day.

**Comment by jacktheboss220** [comment]
I got it. Thanks
