### ISSUE TITLE
[Feature Request] Show current time and Google search

### ISSUE THREAD

**Issue by DarremMolko** [phaticusthiccy/WhatsAsenaDuplicated#197]
As I said in the Support group, it would be nice to have a command to see the current time in certain places, here's how I imagine it:
**Command**: .ctime Hanoi, Vietnam
**Output**:  
`Current time in Hanoi, Vietnam is 12:00 a.m. 16/09/2021`

Also a command to search through Google, for example:
**Command**: .google cupcakes recipe
**Output**: 
```
2 Results for your query: 
¡How to make cupcakes!
https://example.com/cupcakes-recipe
Easy way to make cupcakes
https://example2.net/easy-cupcakes
```

**Comment by phaticusthiccy** [comment]
Hi @DarremMolko 

I will make an external plugin for time module. You can check out the [plugin channel](https://t.me/remasterplugin) in the coming hours.

##

The Google Search, in the new version of WhatsAsena, i will make a pure API without any orientation, bridges or access tokens. It will fetch API from organic google servers. You can wait for it.

**Comment by DarremMolko** [comment]
@phaticusthiccy that's amazing! Thanks again for all your hard work ☺️

**Comment by phaticusthiccy** [comment]
[Time Module](https://t.me/remasterplugin/49) Published on Plugin Channel
