### ISSUE TITLE
WhatsAsena on CMD ( Help )

### ISSUE THREAD

**Issue by HAMODE3389** [phaticusthiccy/WhatsAsenaDuplicated#198]
Hi,

I want to use WhatsAsena through Windows CMD ( Not Heroku )
I tried make config.env and set Heroku to False.

![image](https://user-images.githubusercontent.com/46901427/133708027-957b9296-05e6-4f4c-9cdd-5d8bb83222f4.png)

**Comment by phaticusthiccy** [comment]
#118

**Comment by phaticusthiccy** [comment]
Aslo ı realized, you cloned specific branch to your device. 
You must use `git clone https://github.com/phaticusthiccy/WhatsAsenaDuplicated`

**Comment by phaticusthiccy** [comment]
Your environment are wrong. Please check example.env file again. Also you must set an Heroku API key and APP NAME even if you don't want to install it on heroku servers. 

My advice to you, you shouldn't use it on local. If you don't have a super computer, probably Eva may crash your device. Eva is the most powerful AI in WhatsAsena. WhatsAsena uses real neural networks to interact eva and these things needs to so many work power and millions of kilobytes. Heroku always better for users.

**Comment by HAMODE3389** [comment]
I just renamed example.env and edit some things, ASENA_SESSION included.

I added API key , APP Name , and I got this error...

![image](https://user-images.githubusercontent.com/46901427/133776569-74ac8977-3fa3-4737-8352-9790ce40cab8.png)

Also I have ( I5-9600KF CPU - 16 RAM - Up to 800 Megabits/s Download and 120 Megabits/s upload ) Is it enough to run it ?

Actually, Heroku looks awesome, But I want to edit the code, Is it possible ?

**Comment by phaticusthiccy** [comment]
First think you must know, you cannot edit the codes. Please check #185 

Also you cannot deploy it without creating app on heroku

**Comment by HAMODE3389** [comment]
I cannot edit the codes at all ? 

for example change .asena to .menu

or change the reply of .asena , as you can see there is problem with it

![1](https://user-images.githubusercontent.com/46901427/133779891-5905537a-86ac-4cd7-b084-6190ca688ec9.jpg)

Also quick question, What is the difference between WhatsAsena Public & Private , what should I use ?

**Comment by phaticusthiccy** [comment]
This problem caused by your WhatApp or phone font style. 
WhatAppa includes `[*, _, ~, ```]` types of font options. If it doesn't work on your phone, its not about WhatApp or WhatsAsena, its about your phone or 3rd WhatApp applications.

You cannot edit the codes or menu. Even if you did i, WhatsAsena will not work that moment. Maybe ı can add some menu styles in the future.

WhatsAsena has two worktype. Public and Private (Kid Mode Coming Soon). As the name suggests; private means no one can use your bot. The private. And public means, everyone can use your bot but only admin and personal commands not allowed for public usage

**Comment by HAMODE3389** [comment]
Yeah, you're right, I tried to open it from whatsapp web and it looks fine.

I hope you add category style or make 2 commands , one for commands by category, and the other for all commands.

I recommend you to remove ●▬▬▬  ▬▬▬● from above, It makes it a bit weird, I found " - WhatsAsena Public -" or something like that simple and clean.

Commands and Description style looks great.

Also you should separate owner commands like .install or .shutdown from normal user commands. 

Thanks, I think I will go with Herkou then, without change any codes

**Comment by phaticusthiccy** [comment]
Thanks for precious proposals. We will definitely consider these suggestions. 
Have a nice day.
