### ISSUE TITLE
[Feature Request] Simple Features List

### ISSUE THREAD

**Issue by HAMODE3389** [phaticusthiccy/WhatsAsenaDuplicated#199]
Features Request List | If it included, correct me.

**.GetMeme** ( Give you a random meme )
**.Custom** Command/Replay ( Create Custom Command )
**.NewPoll .Poll .Vote .INS** "add options to vote" ( Create Group Poll )
**.Steal** Pack/Author ( Steal Sticker to Custom Name )
**.Autosticker** on/off ( Auto convert Photos/Videos Into stickers )
**.webshot** ( Screenshot of whatsapp web )
**.menu** ( Simple Category Commands List ) | .Stickers ( All Stickers Commands ) | .Maker ( All Image maker Commands )...

**Comment by phaticusthiccy** [comment]
Hi @HAMODE3389 

Thanks for your valuable suggestions. Here are the answers to your questions:

1) **GetMeme** module would be nice. When I have free time I will make a module for it.
2) We are releasing external plugins officially on our [Telegram Channel.](https://t.me/remasterplugin) You can check there. There is three lessions to how to make plugin. But one thing you must know, these lessions are only turkish. You should translate it.
3) I don't think there is a survey filling system on WhatsApp. This can only be done with a 3rd party application. Voting can be done via the given link.
4) Currently WhatsAsena dosent support change or write exif information on sticker. In the future ı will add it.
5) Autosticker module little bit useless. You can use `.vsticker` to convert animated sticker to video. Also you can use `.sticker` to convert any images or videos (max 10 sec) to sticker.
6) These is a already command for it. You can use `.ss` But sometimes it won't work. I will make an pure API for that.
7) If you want to see full command list, you must use `.asena`

Have a nice day.
