### ISSUE TITLE
ADD Upload module

### ISSUE THREAD

**Issue by justinthoms** [phaticusthiccy/WhatsAsenaDuplicated#2]
pless write up-load module

**Comment by phaticusthiccy** [comment]
> pless write up-load module
Maybe later, sorry

**Comment by phaticusthiccy** [comment]
If you have a suggestion, please use the pull request section.
Have a nice day.

**Comment by Mrvishal2k2** [comment]
Any updates regarding this ....???

**Comment by phaticusthiccy** [comment]
> Any updates regarding this ....???

Sorry, it still does not seem to be make this.
