### ISSUE TITLE
Blur Gifs - Unplayable Sounds - .tagall 

### ISSUE THREAD

**Issue by HAMODE3389** [phaticusthiccy/WhatsAsenaDuplicated#200]
Using Commands Like .textheart .animegif give me Blur - Unplayable Gif.
When I press on it, It shows me black screen.

![11](https://user-images.githubusercontent.com/46901427/133831541-fe888234-d2f0-451c-bb54-b64db72d11a8.jpg)
![22](https://user-images.githubusercontent.com/46901427/133831557-ea8d00cf-831e-4b09-8774-040f77a0f16b.jpg)

Using Command Like .song .tts give me Unplayable sound.
I can't press play button ( When I touch it nothing happen at all ).

![44](https://user-images.githubusercontent.com/46901427/133831954-deb012db-56f5-446b-9f99-ad03b3d9feb1.jpg)
![33](https://user-images.githubusercontent.com/46901427/133831959-fad67d15-232e-4a0e-a63c-4d29475fb8ab.jpg)

.tagall not working, .tagadmin works fine.

![123](https://user-images.githubusercontent.com/46901427/133832689-9192b411-17d6-4419-9f53-d9ff80f148eb.jpg)

**Comment by phaticusthiccy** [comment]
Hi @HAMODE3389 

I know some textmaker gifs and animegif modules. I will fix it in new version. You can use `.sticker` to play these. Then you can use .`vstciker`.

If you using device which including IOS, the audios won't playable. IOS dosent support to mp3 and m4a versions. Also IOS doesn't have enough mimetype and decoders to decrypt song data. That's way the android is the best.

As I said in previous issue, some command not usable for other users. Like tagall. Use it on your bot account.

**Comment by HAMODE3389** [comment]
I think tagall must be usable, It's important command.

IDK , But I found this code in other bot, It may help you...

> 			case 'tagall':
> 				if (isGroupMsg && isGroupAdmins || isGroupMsg && isOwner) {
> 					let hehe = `${body.slice(10)}`
> 					for (let i = 0; i < groupMembers.length; i++) { hehe += `- @${groupMembers[i].id.replace(/@c.us/g, '')}\n` }
> 					hehe += ''
> 					await sleep(2000)
> 					await kill.sendTextWithMentions(from, hehe)
> 				} else if (isGroupMsg) {
> 					await kill.reply(from, mess.soademiro(), id)
> 				} else return await kill.reply(from, mess.sogrupo(), id)
> 				break

**Comment by phaticusthiccy** [comment]
Its easy to implement it. Maybe in the future i can do this. Also the code you sent is not suitable for WhatsAsena. This code is copied from WhatsApp Bot. WhatsAsena is the world first **UserBot** for WhatApp. We coded WhatsAsena with our unique codding style.

**Comment by HAMODE3389** [comment]
So...

Blur Gifs issue will solve in future.
Unplayable Sounds issue won't work in IOS but works fine in android.
.tagall issue will also solve in future.

Right ?

**Comment by phaticusthiccy** [comment]
The answers of questions:

1) Yes, ı will fix it.
2) IOS devices always worse than android. 
3) The not working `.tagall` command in public, its not an issue. Just an unsupported module for public users.
