### ISSUE TITLE
Installing sqlite3 on Termux 

### ISSUE THREAD

**Issue by Temuxuser2021** [phaticusthiccy/WhatsAsenaDuplicated#201]
**Describe the bug**
node bot.js
/data/data/com.termux/files/home/WhatsAsenaDuplicated/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81
        throw new Error(`Please install ${moduleName} package manually`);
        ^

Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/data/data/com.termux/files/home/WhatsAsenaDuplicated/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/data/data/com.termux/files/home/WhatsAsenaDuplicated/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
    at new SqliteDialect (/data/data/com.termux/files/home/WhatsAsenaDuplicated/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
    at new Sequelize (/data/data/com.termux/files/home/WhatsAsenaDuplicated/node_modules/sequelize/lib/sequelize.js:340:20)
    at Object.<anonymous> (/data/data/com.termux/files/home/WhatsAsenaDuplicated/config.js:55:52)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
##

**Expected behavior**
![Uploading Screenshot_2021-09-19-10-44-44-05.jpg…]()
![Uploading Screenshot_2021-09-19-10-44-04-52_84d3000e3f4017145260f7618db1d683.jpg…]()

##

**Screenshots**

##

**Users, please complete the following actions.**
- WhatApp Package Name
- WhatsAsena Version
- Work Type (Private || Public)

##

**Additional context**

**Comment by phaticusthiccy** [comment]
Hi @Temuxuser2021 

If you want to install WhatsAsena on your local storage, you must install packages manually. There is a sqlite3 error. 

Sqlite3, dosent support some arm64 and armx86 devices. In this case, there are a few ways to do. 

##

## Installing Pre-Relased Packages 
`$ pkg install clang libsqlite pkg-config python make `
`$ pkg install pkg-config `
`$ pkg install clang libsqlite pkg-config `
`$ npm install sqlite3 --node-trace`

## Force to Install ( Only Localhost )
`$ npm install sqlite3 --build-from-source --sqlite=~/../usr/bin/sqlite3
npm install better-sqlite3 --sqlite=./sqlite-amalgamation`

## Make Way
`$ pkg install build-essential`
`$ pkg install make`
`$ npm i sqlite3`

## Experimental Way
`$ apt install libllvm`
`$ apt install clang make nodejs-dev libuv-dev`
`$ apt install g++`
`$ npm install sqlite3`

##

Try these, if there are any problems your device may not support it.

**Comment by Temuxuser2021** [comment]
Yes , i use all method (commands) but the same probelm accours , i think its problem on the script can you please check in your other phone ? 😸

**Comment by phaticusthiccy** [comment]
> Try these, if there are any problems your device may not support it.

I think your device dosent support databae colons with sqlite3

**Comment by Temuxuser2021** [comment]
> > Try these, if there are any problems your device may not support it.
> 
> I think your device dosent support databae colons with sqlite3

😔.  Hope its work

**Comment by Temuxuser2021** [comment]
![Screenshot_2021-09-21-08-02-13-70_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/87321079/134103019-7b0ff9a1-4f07-4bd4-a1b5-018075126eb7.jpg)
   

 See the screenshot i do all the thing but not working im using termux  new version

**Comment by Temuxuser2021** [comment]
So how can i use it my phone is oppo a15 android 10 ram 3gb 😟 can i install on virutual space like , vmos,v1m,x8sandbox.etc 🙂

**Comment by phaticusthiccy** [comment]
Its not about your termux version. Some android architectures dosent support sqlite3 requirements. I don't know which models support or don't support it. If none of the above ways work, probably your phone can't handle it.

Yeah, you can install WhatsAsena on vds, vps or any virtual device. Set sudo user on your host called **/root/WhatsAsenaDuplicated** run it on there. But we are not recommend this way, it will just be a waste of space as you can't change the codes.
