### ISSUE TITLE
Not logging in when multi login is enabled! #51

### ISSUE THREAD

**Issue by denomparkour** [phaticusthiccy/WhatsAsenaDuplicated#203]
**Describe the bug**
When I try to login when multilogin enabled it shows this following error

```
WARN [2021-09-19 13:11:11.084 +0000] (8608): connect attempt 2 failed: Error: close, retrying...
    class: "Baileys"
    error: {}
```

**Comment by phaticusthiccy** [comment]
Hi @denomparkour 

These features are special for WhatApp Beta testers. We must wait until the public release. Also WhatsAsena based on Baileys Framework, so that's means we should wait for the Baileys update.
