### ISSUE TITLE
i tried using the hard method. (running it locally)

### ISSUE THREAD

**Issue by rishabh-modi2** [phaticusthiccy/WhatsAsenaDuplicated#208]
**Describe the bug**
i tried using the hard method. (running it locally).
you should once try hard method.
i done whatever you written in the hard method

##

**Expected behavior**

##

**Screenshots**

##

**Users, please complete the following actions.**
- WhatApp Package Name
- WhatsAsena Version
- Work Type (Private || Public)

##

**Additional context**

**Comment by phaticusthiccy** [comment]
Please, fill the required forms.

**Comment by satyammayy** [comment]
not workingggg for me locally too
