### ISSUE TITLE
Baileys error

### ISSUE THREAD

**Issue by jacktheboss220** [phaticusthiccy/WhatsAsenaDuplicated#217]
![WhatsApp Image 2021-11-02 at 10 29 21 AM](https://user-images.githubusercontent.com/81576386/139794411-13257221-9d92-46ef-ae17-ab4d28201cbe.jpeg)

this can fix the Baileys error .

**Comment by phaticusthiccy** [comment]
[Content](https://github.com/adiwajshing/Baileys/issues/782#issuecomment-957034437)

Updating Version

**Comment by phaticusthiccy** [comment]
Commit [#de754d8](https://github.com/phaticusthiccy/WhatsAsenaDuplicated/commit/de754d8f1f00fc2dd1f7f3caaf04350bb70fc720)

**Comment by jacktheboss220** [comment]
thnx 😊

**Comment by Nimuzzz** [comment]
somebody help me to solve this. i am not able to use it
