### ISSUE TITLE
Can't generate asena session

### ISSUE THREAD

**Issue by ThizPersonDoesNotExist** [phaticusthiccy/WhatsAsenaDuplicated#221]
![2021-11-16 (7)](https://user-images.githubusercontent.com/84295640/141956898-7e7d0ac9-b955-464d-baf7-926542564871.png)
![2021-11-16 (25)](https://user-images.githubusercontent.com/84295640/141956959-f1b4c890-a9de-4407-872e-e8d475ed7f30.png)

**Comment by ThizPersonDoesNotExist** [comment]
Working in older version of whatsapp
Unable to scan in latest version of multi-device version

**Comment by phaticusthiccy** [comment]
WhatsAsena dosent support multi-device yet. Please disable the MD feature.

**Comment by dark-coder-cat** [comment]
> WhatsAsena dosent support multi-device yet. Please disable the MD feature.

it's now started rolling out publically.

**Comment by Sanskar879637thgi** [comment]
same problem and how to figure it out
