### ISSUE TITLE
webp2mp4File not working anymore

### ISSUE THREAD

**Issue by aymenitc** [phaticusthiccy/WhatsAsenaDuplicated#232]
Converting animated stickers back to gif

webp2mp4File
Not working anymore I get error
`TypeError: Cannot read property 'name' of null at FormData._getContentDisposition `

**Comment by phaticusthiccy** [comment]
Dear User
We are no longer providing support for WhatsAsena. We will be ending support with a final update, soon. I logged this error. I will push update to fix this bug. 

Thanks for using WhatsAsena.

**Comment by dark-coder-cat** [comment]
> Dear User
> We are no longer providing support for WhatsAsena. We will be ending support with a final update, soon. I logged this error. I will push update to fix this bug. 
> 
> Thanks for using WhatsAsena.

What about multi-device? will it be made or dropped off.
