### ISSUE TITLE
PLEASE ADD WHATSAPP MULTI DEVICE SUPPORT

### ISSUE THREAD

**Issue by debojit16mitra** [phaticusthiccy/WhatsAsenaDuplicated#251]
PLEASE ADD WHATSAPP MULTI DEVICE SUPPORT. THANK YOU

**Comment by phaticusthiccy** [comment]
Development for WhatsAsena is no longer available. Please check my other project called [Primon Proto](https://github.com/phaticusthiccyPrimonProto)

**Comment by anshuguruji** [comment]
How to use primonProto

**Comment by phaticusthiccy** [comment]
Primon Proto still under development. I still have a few things to work on. If you want to follow the announcements and innovations, you can join the https://t.me/AsenaSupport channel.
