### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by kikiixyz** [phaticusthiccy/WhatsAsenaDuplicated#3]
switch Self mode and public mode

**Comment by phaticusthiccy** [comment]
> switch Self mode and public mode

So, did u mean anyone who doesn't have a WhatsAsena can use it?

**Comment by kikiixyz** [comment]
> So, did u mean anyone who doesn't have a WhatsAsena can use it?

That's not it, bro, like that, self mode is for ourselves and public mode allows everyone to use bot commands

**Comment by phaticusthiccy** [comment]
> > So, did u mean anyone who doesn't have a WhatsAsena can use it?
> 
> That's not it, bro, like that, self mode is for ourselves and public mode allows everyone to use bot commands

Maybe ı'll handle it. But not for now. Sorry

**Comment by kikiixyz** [comment]
> Maybe ı'll handle it. But not for now. Sorry

okay calm

**Comment by phaticusthiccy** [comment]
If you have a suggestion, please use the pull request section.
Have a nice day.
