### ISSUE TITLE
Filters to global

### ISSUE THREAD

**Issue by moca-stgm** [phaticusthiccy/WhatsAsenaDuplicated#5]
well, i hope you can add fitur on the filter to global, so the filter we have set is able to send to a whole new message on other chat.

**Comment by phaticusthiccy** [comment]
I need to change the sql file for to do this. Moreover, global filters can cause some problems.. 
Maybe i ll handle it. But sorry for now.

**Comment by phaticusthiccy** [comment]
If you have a suggestion, please use the pull request section.
Have a nice day.

**Comment by moca-stgm** [comment]
oh yes, really sorry put this request on issue
