### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by bagusdwip** [phaticusthiccy/WhatsAsenaDuplicated#57]
Sticker Wm 
FB download

**Comment by phaticusthiccy** [comment]
### Hi @bagusdwip 

Sticker WM? Can you explain a little more?
Wait for the new update for Facebook Downloader :)

**Comment by bagusdwip** [comment]
> ### Hi @bagusdwip
> Sticker WM? Can you explain a little more?
> Wait for the new update for Facebook Downloader :)

Sticker Which has a sign / water mark 
Some WhatsApp stickers have a water mark if we click on the sticker
