### ISSUE TITLE
how to move plugins to simple commands

### ISSUE THREAD

**Issue by kikiixyz** [phaticusthiccy/WhatsAsenaDuplicated#7]
example :+1: 
`if (txt.startsWith("hii") {
conn.sendMessage(toId, 'haloo', MessageType.text)`

**Comment by MuhammedKpln** [comment]
This will bring multiple problems as well. 

- If we do this in this way we won't have control over the commands.
- Help page won't display help either because of we don't know what plugin is added or not
- It is not developer friendly.
