### ISSUE TITLE
PmPermit.js

### ISSUE THREAD

**Issue by thecyberbyte-tech** [phaticusthiccy/WhatsAsenaDuplicated#90]
**hey bro**
**Some spammer does spammming using your UserBot.** Can you create a PmPermit plugin like https://github.com/TheWhatsBot/WhatsBot/blob/main/modules/pmpermit.js

it's great if you create it soon

**Thank You**

**Comment by phaticusthiccy** [comment]
This may take while. I can add in the future, stand by for now.
